export const SIGNUP_CHANGE_EMAIL_ERROR_TEXT = "SIGNUP_CHANGE_EMAIL_ERROR_TEXT" as const;
export const SIGNUP_CHANGE_NICKNAME_ERROR_TEXT = "SIGNUP_CHANGE_NICKNAME_ERROR_TEXT" as const;
export const SIGNUP_CHANGE_PASSWORD_ERROR_TEXT = "SIGNUP_CHANGE_PASSWORD_ERROR_TEXT" as const;
export const SIGNUP_CHANGE_PASSWORD_CONFIRM_ERROR_TEXT = "SIGNUP_CHANGE_PASSWORD_CONFIRM_ERROR_TEXT" as const;
